filebeat.prospectors:
- input_type: log
  paths: ["/mnt/ep_logs/*.json"]
  json.message_key: event
  json.keys_under_root: true
#  fields:
#    planet: Magrathea
#    service: ${SERVICE_NAME}
#  tags: [
#    "i",
#    "heart",
#    "json"
#  ]

output.elasticsearch:
  hosts: ["elk:9200"]
  template.name: filebeat
  template.path: /etc/filebeat/filebeat.template.json
